### ISSUE TITLE
Swift Package Manager compatibility

### ISSUE THREAD

**Issue by Samasaur1** [aaplmath/CaffeineKit#1]
In order to make this a SPM-compatible library, it needs to have a git tag. According to the [documentation](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md):

> Simply put: a package is a git repository with semantically versioned tags, that contains Swift sources and a Package.swift manifest file at its root.

Currently, CaffeineKit meets ¾ of the requirements.

- [x] Git repository
- [x] Swift sources
- [x] `Package.swift` file
- [x] Contains tags

**Comment by jrr6** [comment]
That's why it's labeled "under development" 😃

Once it's stable (read: tested) enough for an alpha release, I'll tag it.

**Comment by Samasaur1** [comment]
Just by the way, in case anyone wants to use this right now, you can do this:
```swift
.package(url: "https://github.com/aaplmath/CaffeineKit", .branch("master"))
```
in the `dependencies` section of your `Package.swift`.

**Comment by jrr6** [comment]
Now tagged with `v0.1.0`, so closing this issue.
